### ISSUE TITLE
Could you provide the scripts to create the KG datafiles?

### ISSUE THREAD

**Issue by sarahwie** [thu-coai/CommonsenseStoryGen#3]
Specifically, to take the ATOMIC and ConceptNet resources, perform delexicalization, and turn them into train/dev/test

**Comment by JianGuanTHU** [comment]
We have uploaded the processed commonsense data [here](https://cloud.tsinghua.edu.cn/d/670f7787b6554f308226/).

**Comment by sarahwie** [comment]
Thanks.
