### ISSUE TITLE
the training result

### ISSUE THREAD

**Issue by 1245244103** [thu-coai/CommonsenseStoryGen#8]
I run the code,and find the PPL on validation set getting bigger and bigger. Did anyone have the same problem with me?
![image](https://user-images.githubusercontent.com/58716304/114298557-8be48980-9ae9-11eb-9a30-4d9d3ef8e57a.png)

**Comment by ccSoVegetable** [comment]
Hi, I am trying this code and meet the same problem as you described above. Could you please tell me how you deal with this problem? Thank you!
